package codec

import (
	"encoding/binary"
	"fmt"
	"io"
	"os"
)

const (
	staticPPMMagic   = "PPM3"
	staticPPMVersion = 1
)

// StaticPPMSymbol is one symbol/frequency pair.
type StaticPPMSymbol struct {
	Symbol byte
	Count  uint32
}

// StaticPPMContext is an immutable trained context.
type StaticPPMContext struct {
	Key     uint32
	Order   uint8
	Total   uint32
	Symbols []StaticPPMSymbol
}

// StaticPPM is the runtime representation of ppm3.bin.
//
// Unlike PPMModel, this model never changes while encoding or decoding.
// The context is determined entirely by the preceding bytes.
type StaticPPM struct {
	MaxOrder uint8

	contexts map[uint64]*StaticPPMContext
}

// NewStaticPPM creates an empty static model.
func NewStaticPPM() *StaticPPM {
	return &StaticPPM{
		contexts: make(map[uint64]*StaticPPMContext),
	}
}

func staticPPMContextKey(order uint8, key uint32) uint64 {
	return (uint64(order) << 32) | uint64(key)
}

// LoadStaticPPM loads a model generated by cmd/ppm_trainer.
func LoadStaticPPM(path string) (*StaticPPM, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open PPM model: %w", err)
	}
	defer file.Close()

	model := NewStaticPPM()

	var magic [4]byte

	if _, err := io.ReadFull(file, magic[:]); err != nil {
		return nil, fmt.Errorf("read PPM magic: %w", err)
	}

	if string(magic[:]) != staticPPMMagic {
		return nil, fmt.Errorf(
			"invalid PPM magic %q",
			string(magic[:]),
		)
	}

	var version uint8

	if err := binary.Read(
		file,
		binary.BigEndian,
		&version,
	); err != nil {
		return nil, fmt.Errorf("read PPM version: %w", err)
	}

	if version != staticPPMVersion {
		return nil, fmt.Errorf(
			"unsupported PPM version %d",
			version,
		)
	}

	var maxOrder uint8

	if err := binary.Read(
		file,
		binary.BigEndian,
		&maxOrder,
	); err != nil {
		return nil, fmt.Errorf("read PPM max order: %w", err)
	}

	if maxOrder > 3 {
		return nil, fmt.Errorf(
			"unsupported PPM max order %d",
			maxOrder,
		)
	}

	model.MaxOrder = maxOrder

	// Training percentage.
	// We don't currently need this at runtime.
	var trainPercent uint8

	if err := binary.Read(
		file,
		binary.BigEndian,
		&trainPercent,
	); err != nil {
		return nil, fmt.Errorf(
			"read PPM train percentage: %w",
			err,
		)
	}

	// Reserved byte.
	var reserved uint8

	if err := binary.Read(
		file,
		binary.BigEndian,
		&reserved,
	); err != nil {
		return nil, fmt.Errorf(
			"read PPM reserved byte: %w",
			err,
		)
	}

	var totalURLs uint64
	var trainURLs uint64
	var contextCount uint64

	if err := binary.Read(
		file,
		binary.BigEndian,
		&totalURLs,
	); err != nil {
		return nil, fmt.Errorf(
			"read total URL count: %w",
			err,
		)
	}

	if err := binary.Read(
		file,
		binary.BigEndian,
		&trainURLs,
	); err != nil {
		return nil, fmt.Errorf(
			"read training URL count: %w",
			err,
		)
	}

	if err := binary.Read(
		file,
		binary.BigEndian,
		&contextCount,
	); err != nil {
		return nil, fmt.Errorf(
			"read context count: %w",
			err,
		)
	}

	if contextCount == 0 {
		return nil, fmt.Errorf("PPM model contains no contexts")
	}

	if contextCount > 10_000_000 {
		return nil, fmt.Errorf(
			"PPM context count is unreasonable: %d",
			contextCount,
		)
	}

	_ = trainPercent
	_ = totalURLs
	_ = trainURLs
	_ = reserved

	model.contexts = make(
		map[uint64]*StaticPPMContext,
		int(contextCount),
	)

	for i := uint64(0); i < contextCount; i++ {
		var key uint32
		var total uint32
		var symbolCount uint8

		if err := binary.Read(
			file,
			binary.BigEndian,
			&key,
		); err != nil {
			return nil, fmt.Errorf(
				"read context %d key: %w",
				i,
				err,
			)
		}

		if err := binary.Read(
			file,
			binary.BigEndian,
			&total,
		); err != nil {
			return nil, fmt.Errorf(
				"read context %d total: %w",
				i,
				err,
			)
		}

		if err := binary.Read(
			file,
			binary.BigEndian,
			&symbolCount,
		); err != nil {
			return nil, fmt.Errorf(
				"read context %d symbol count: %w",
				i,
				err,
			)
		}

		if symbolCount == 0 {
			return nil, fmt.Errorf(
				"context %d contains no symbols",
				i,
			)
		}

		context := &StaticPPMContext{
			Key:     key,
			Order:   0,
			Total:   total,
			Symbols: make([]StaticPPMSymbol, symbolCount),
		}

		for j := 0; j < int(symbolCount); j++ {
			if err := binary.Read(
				file,
				binary.BigEndian,
				&context.Symbols[j].Symbol,
			); err != nil {
				return nil, fmt.Errorf(
					"read context %d symbol %d: %w",
					i,
					j,
					err,
				)
			}

			if err := binary.Read(
				file,
				binary.BigEndian,
				&context.Symbols[j].Count,
			); err != nil {
				return nil, fmt.Errorf(
					"read context %d count %d: %w",
					i,
					j,
					err,
				)
			}

			if context.Symbols[j].Count == 0 {
				return nil, fmt.Errorf(
					"context %d contains zero-frequency symbol",
					i,
				)
			}
		}

		/*
			The file stores contexts sorted by:

			    order
			    context key

			but only stores the uint32 context key here.

			The order can be recovered from the fact that the
			context key itself does not contain the order, so we
			need to derive it while loading.

			Because the binary format doesn't explicitly store it,
			we determine it from the key width according to the
			model's maximum order.

			For order 0, key is always zero.
			For higher orders, leading zero bytes are possible,
			so the order cannot actually be inferred reliably.

			Therefore the trainer's current format needs one small
			compatibility rule: contexts are reconstructed by trying
			all possible orders when looked up.

			We insert the context into every possible order whose
			context key matches during runtime lookup.
		*/

		model.contexts[staticPPMContextKey(0, key)] = context
	}

	/*
		The current trainer format does not serialize the context
		order separately. That means the model cannot distinguish:

		    order 1: "a"
		    order 2: "\x00a"
		    order 3: "\x00\x00a"

		without additional metadata.

		Reject this format here rather than silently loading an
		incorrect model.
	*/
	return nil, fmt.Errorf(
		"PPM3 model format v1 is missing context-order metadata; regenerate the model with the corrected trainer format",
	)
}
